"""LLM agent helpers for iterative, search-oriented generation workflows."""

from .generation import (
    ActorRolloutStep,
    ContinuationDecision,
    FinalGenBatchOutput,
    GRPOPromptGroupResult,
    GRPORolloutSafetyConfig,
    GRPOTrainingStepResult,
    GroupedRolloutBatch,
    ScoredGroupedRollout,
    SearchStep,
    SearchTrajectoryLog,
    GenerationConfig,
    LLMGenerationManager,
    PPOPolicyLossConfig,
    ReActContextTransition,
    SearchBatch,
    SearchDecision,
    apply_rollout_safety_penalties,
    apply_safety_penalties_to_scored_rollouts,
    async_run_prompt_rollout_group,
    format_group_rollout,
    format_scored_group_rollout,
    assign_group_relative_advantages,
    format_search_trajectory_log,
    format_trajectory_batch,
    save_training_batch_jsonl,
    score_group_rollout,
    trajectory_log_prob_pack,
    compute_trajectory_policy_loss,
)
from .tensor_helper import TensorConfig, TensorHelper

__all__ = [
    "ActorRolloutStep",
    "ContinuationDecision",
    "FinalGenBatchOutput",
    "GenerationConfig",
    "GRPOPromptGroupResult",
    "GRPORolloutSafetyConfig",
    "GRPOTrainingStepResult",
    "GroupedRolloutBatch",
    "LLMGenerationManager",
    "PPOPolicyLossConfig",
    "ReActContextTransition",
    "ScoredGroupedRollout",
    "SearchBatch",
    "SearchDecision",
    "SearchStep",
    "SearchTrajectoryLog",
    "TensorConfig",
    "TensorHelper",
    "apply_rollout_safety_penalties",
    "apply_safety_penalties_to_scored_rollouts",
    "async_run_prompt_rollout_group",
    "assign_group_relative_advantages",
    "format_group_rollout",
    "format_scored_group_rollout",
    "format_search_trajectory_log",
    "format_trajectory_batch",
    "save_training_batch_jsonl",
    "score_group_rollout",
    "trajectory_log_prob_pack",
    "compute_trajectory_policy_loss",
]
