"""Agent loop utilities for local generation workflows."""

from .agent_loop import (
    AgentLoopBase,
    AgentLoopConfig,
    AgentLoopOutput,
    RolloutStep,
    get_registered_agent_loop,
    list_registered_agent_loops,
    register,
    simple_timer,
)
from .context import AgentContext, SearchContext, SearchResult
from .data import (
    DEFAULT_TOOL_SYSTEM_PROMPT,
    PromptBatch,
    PromptOnlyDataset,
    PromptSample,
    PromptTrainingExample,
    build_prompt_dataloader,
    build_prompt_ids_from_messages,
    build_prompt_messages,
    collate_prompt_batch,
    normalize_prompt_training_example,
    prompt_batch_to_search_batch,
)
from .evaluation import (
    QueryEvaluation,
    SearchEvaluationConfig,
    SearchResultEvaluator,
    SearchRoundEvaluation,
)
from .intent_classifier import (
    INTENT_LABELS,
    IntentPipeline,
    IntentPrediction,
    IntentionClassificationPipeline,
    load_training_data as load_intent_training_data,
    resolve_search_settings,
)
from .grpo import (
    GRPOAdvantageConfig,
    GRPORolloutSample,
    PromptGroupSamplingConfig,
    ScoredGRPORollout,
    build_grpo_sampling_params,
    compute_grpo_outcome_advantage,
    sample_prompt_group,
    score_prompt_group,
)
from .reward import (
    BatchJudgeFn,
    JudgeFn,
    SearchRewardConfig,
    SearchRewardFunction,
    normalize_answer_text,
    simple_sparse_correctness_reward,
)
from .search_agent_loop import (
    SearchAgentLoop,
    SearchAgentLoopConfig,
    SearchRoundResult,
    SearchToolCall,
    build_search_agent_instruction,
)
from .sft import SFTExample, build_search_sft_example
from .search_client import SearchClient, SearchClientConfig
from .single_turn_agent_loop import SingleTurnAgentLoop
from .tool import FunctionTool, Tool, ToolSchema
from .tool_agent_loop import ToolAgentLoop, ToolAgentLoopConfig
from .tool_parser import (
    FunctionCall,
    HermesToolParser,
    JSONToolParser,
    Llama3ToolParser,
    ToolParser,
)

__all__ = [
    "AgentContext",
    "GRPOAdvantageConfig",
    "build_grpo_sampling_params",
    "compute_grpo_outcome_advantage",
    "build_prompt_dataloader",
    "build_prompt_ids_from_messages",
    "build_prompt_messages",
    "prompt_batch_to_search_batch",
    "BatchJudgeFn",
    "JudgeFn",
    "SearchRewardConfig",
    "SearchRewardFunction",
    "normalize_answer_text",
    "simple_sparse_correctness_reward",
    "AgentLoopBase",
    "AgentLoopConfig",
    "AgentLoopOutput",
    "RolloutStep",
    "build_search_agent_instruction",
    "collate_prompt_batch",
    "DEFAULT_TOOL_SYSTEM_PROMPT",
    "FunctionCall",
    "FunctionTool",
    "HermesToolParser",
    "INTENT_LABELS",
    "IntentPipeline",
    "IntentPrediction",
    "IntentionClassificationPipeline",
    "load_intent_training_data",
    "GRPORolloutSample",
    "PromptGroupSamplingConfig",
    "resolve_search_settings",
    "JSONToolParser",
    "Llama3ToolParser",
    "normalize_prompt_training_example",
    "PromptBatch",
    "PromptOnlyDataset",
    "PromptSample",
    "PromptTrainingExample",
    "QueryEvaluation",
    "SearchAgentLoop",
    "SearchAgentLoopConfig",
    "SearchRoundResult",
    "SearchToolCall",
    "SFTExample",
    "SearchClient",
    "SearchClientConfig",
    "SearchContext",
    "SearchEvaluationConfig",
    "SearchResult",
    "SearchResultEvaluator",
    "SearchRoundEvaluation",
    "ScoredGRPORollout",
    "SingleTurnAgentLoop",
    "build_search_sft_example",
    "sample_prompt_group",
    "score_prompt_group",
    "Tool",
    "ToolAgentLoop",
    "ToolAgentLoopConfig",
    "ToolParser",
    "ToolSchema",
    "get_registered_agent_loop",
    "list_registered_agent_loops",
    "register",
    "simple_timer",
]
